### ISSUE TITLE
Build fails with ember-cli-sass installed

### ISSUE THREAD

**Issue by jacobq** [salsify/ember-css-modules#107]
I'm not sure why this is, but if I try to use `ember-css-modules` in a project with `ember-cli-sass` I get an error like the one mentioned in #76.  I have created a repro repo [here](https://github.com/jacobq/ecm-repro-107). Note: `master` (tagged `works`) works but previous commit (tagged `broken`) is broken.

```
$ ember -v
ember-cli: 3.3.0
node: 10.9.0
os: linux x64
```

```
Build Error (SassCompiler)

File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp


Stack Trace and Error Report: /tmp/error.dump.2d108ad67c9388a351868e7c28e65677.log
```

```
$ cat /tmp/error.dump.2d108ad67c9388a351868e7c28e65677.log
=================================================================================

ENV Summary:

  TIME: Mon Aug 27 2018 10:50:11 GMT-0500 (Central Daylight Time)
  TITLE: ember
  ARGV:
  - /home/user/.nvm/versions/node/v10.9.0/bin/node
  - /home/user/.nvm/versions/node/v10.9.0/bin/ember
  - s
  EXEC_PATH: /home/user/.nvm/versions/node/v10.9.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/user/.nvm/versions/node/v10.9.0/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/local/games
  - /usr/games
  - ./node_modules/.bin
  - /home/user/.local/bin
  PLATFORM: linux x64
  FREEMEM: 3717365760
  TOTALMEM: 33689444352
  UPTIME: 5942
  LOADAVG: 0.7734375,0.9658203125,1.1962890625
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4009
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4159
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.9.0
  - openssl: 1.1.0i
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.8.275.24-node.14
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
    at Object.findFileSync (/home/user/tmp/ecm-test/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/home/user/tmp/ecm-test/node_modules/broccoli-sass-source-maps/index.js:84:31)
    at /home/user/tmp/ecm-test/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  - codeFrame: File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SassCompiler` plugin. 💥
File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SassCompiler` plugin. 💥
File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
  - name: Error
  - nodeAnnotation: SassCompiler
  - nodeName: SassCompiler
  - originalErrorMessage: File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
  - stack: Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /home/user/tmp/ecm-test/tmp/sass_compiler-input_base_path-UjzzZT6h.tmp
    at Object.findFileSync (/home/user/tmp/ecm-test/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/home/user/tmp/ecm-test/node_modules/broccoli-sass-source-maps/index.js:84:31)
    at /home/user/tmp/ecm-test/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/user/tmp/ecm-test/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)

=================================================================================
```

**Comment by jacobq** [comment]
Talked with some people on the Ember Community Slack server's "e-css-modules" channel, and they pointed out that I needed to [`ember install ember-css-modules-sass`](https://github.com/dfreeman/ember-css-modules-sass) per the [`README` instructions](https://github.com/salsify/ember-css-modules#plugins). I just wasted half an hour debugging a known/intentional behavior and now feel rather silly. Hopefully others googling the error message that I encountered will find this issue and avoid this pitfall.
