### ISSUE TITLE
Usage within add-on causing error

### ISSUE THREAD

**Issue by ynnoj** [salsify/ember-css-modules#32]
I'm encountering an issue when trying to convert an existing add-on I maintain to use this add-on. I've updated the `index.js` to include the `options` object, but error occurs because of a pre-existing function that imports dependencies into the consuming app.

Guilty file (`index.js`) is viewable [here](https://github.com/stonecircle/ember-cli-notifications/blob/css-rewrite/index.js).

`Cannot read property 'plugins' of undefined
TypeError: Cannot read property 'plugins' of undefined
    at Class.module.exports.getPlugins (/Users/J/git/ember-cli-notifications/node_modules/ember-css-modules/index.js:48:24)
    at ModulesPreprocessor.getPlugins (/Users/J/git/ember-cli-notifications/node_modules/ember-css-modules/lib/modules-preprocessor.js:87:30)
    at ModulesPreprocessor.toTree (/Users/J/git/ember-cli-notifications/node_modules/ember-css-modules/lib/modules-preprocessor.js:43:19)
    at /Users/J/git/ember-cli-notifications/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/J/git/ember-cli-notifications/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/J/git/ember-cli-notifications/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at Class.Addon.preprocessJs (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:724:23)
    at Class.Addon.processedAddonJsFiles (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:736:15)
    at Class.Addon.compileAddon (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:652:22)
    at Class.Addon.treeForAddon (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:403:24)
    at Class._treeFor (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
    at Array.map (native)
    at EmberAddon.EmberApp.addonTreesFor (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
    at EmberAddon._addonTree (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:871:36)
    at EmberAddon.EmberApp._processedVendorTree (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:916:20)
    at EmberAddon.EmberApp._processedExternalTree (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:947:21)
    at EmberAddon.EmberApp.appAndDependencies (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:1043:30)
    at EmberAddon.EmberApp.javascript (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:1159:34)
    at EmberAddon.EmberApp.toArray (/Users/J/git/ember-cli-notifications/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)`

**Comment by dfreeman** [comment]
I think the problem is [this line](https://github.com/stonecircle/ember-cli-notifications/blob/css-rewrite/index.js#L21). `CoreObject`'s `_super` doesn't work like Ember's, so you have to call it like:

```js
this._super.included.call(this, app);
```

Can you give that a try and see if it solves the problem?

**Comment by ynnoj** [comment]
@dfreeman Hey Dan. That fixed it right away.

Awesome, thanks! 👍
