### ISSUE TITLE
Not cooperating with ember-cli-sass

### ISSUE THREAD

**Issue by Kzone272** [salsify/ember-css-modules#55]
After installing ember-css-modules I'm receiving the following errors:
```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /repos/transact/tmp/sass_compiler-input_base_path-TXfUoVjg.tmp/0
    at Object.findFileSync (/repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:63:31)
    at /repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:149:21
    at lib$rsvp$$internal$$tryCatch (/repos/transact/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/repos/transact/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/repos/transact/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/repos/transact/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at SassCompiler.Plugin (/repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/repos/transact/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /repos/transact/node_modules/ember-cli-sass/index.js:39:12
    at Array.map (native)
    at SASSPlugin.toTree (/repos/transact/node_modules/ember-cli-sass/index.js:36:34)
    at /repos/transact/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/repos/transact/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/repos/transact/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```

I'm trying to configure ember-css-modules to work with ember-cli-sass, which appears to be supported, but this error occurs as long as I have both ember-cli-sass and ember-css-modules installed, no matter what `cssModules` options I try.

I've tried this with ember-cli-sass version 5.3.1 and version 5.6.0, and ember-css-modules 0.5.0.

Any ideas?

**Comment by dfreeman** [comment]
From your description I'm guessing you've already looked at the section of the README on [working with other preprocessors](https://github.com/salsify/ember-css-modules#other-preprocessors). Can you share the specific configuration for both ember-css-modules and ember-cli-sass that you've tried? Thanks!

**Comment by Kzone272** [comment]
I just created a new ember project and installed both ember-cli-sass and ember-css-modules to isolate the problem.  I'm seeing the same error above with this configuration:
```
    cssModules: {
      extension: 'scss',
      intermediateOutputPath: 'app/styles/_modules.scss',
    }
```
As well as all combinations of both of those options on and off, including no cssModules at all.  All of this is tested with no custom sassOptions.

I've posted the project here: https://github.com/Kzone272/sass-pods-test

**Comment by dfreeman** [comment]
At a glance, I see a few different things that are likely keeping your setup from working. First off, [your configuration](https://github.com/Kzone272/sass-pods-test/commit/621a4bf12b7d442e8cdea22897b15b0640696ae7#diff-695693c5dabaffb064bde5b060195ff7) will need to be in [`ember-cli-build.js`](https://github.com/salsify/ember-css-modules#configuration) to have any effect 😉.

Second, it looks like you're using a combination of the [two](https://github.com/salsify/ember-css-modules#modules-and-preprocessor-syntax-in-isolation) [approaches](https://github.com/salsify/ember-css-modules#custom-syntax-directly-in-modules) for integrating with Sass suggested by the README, which have different (incompatible) goals. With the setup you gave above, ember-css-modules would pick up your `app.scss` and include it in the `_modules.scss` output file, which means there would be no `app.scss` afterwards for ember-cli-sass to find. If you want all your Sass to be processed as CSS Modules, you can probably just use `app/styles/app.scss` as your `intermediateOutputPath`.

Finally, you'll pretty quickly run into trouble trying to process files with Sass syntax if PostCSS doesn't know what that is. You can teach it how to deal with that by passing in a custom parser:

```js
cssModules: {
  // ...other config...
  postcssOptions: {
    syntax: require('postcss-scss')
  }
}
```

Based on the setup it _looks_ like you're trying for, I expect you can follow the "[custom syntax directly in modules](https://github.com/salsify/ember-css-modules#custom-syntax-directly-in-modules)" directions in the README verbatim.

**Comment by Kzone272** [comment]
Ah that was my problem!  😊

Just for some explanation, I was putting it in environment.js because I was coming from trying to use `ember-component-css`, and didn't catch the difference.

Thanks for the clarification though.  I've now got it working as I'd like it with exactly that section of the readme. 👍
