### ISSUE TITLE
`ember test` fails with error in addon

### ISSUE THREAD

**Issue by deverstalmage** [salsify/ember-css-modules#66]
`ember-cli`: 2.12.0
`ember-source`: 2.12.0
`ember-css-modules`: 0.6.5

Created a new addon via `ember addon`, added an `addon/styles` directory with a `.placeholder` file inside and I get this error when I run `ember test`:

```
Error: Unable to provide the modules tree before the preprocessor has been invoked
    at ModulesPreprocessor.getModulesTree (/Users/devers/Projects/test-engine/node_modules/ember-css-modules/lib/modules-preprocessor.js:21:11)
    at Class.getModulesTree (/Users/devers/Projects/test-engine/node_modules/ember-css-modules/index.js:78:37)
    at OutputStylesPreprocessor.dynamicHeaderConcat (/Users/devers/Projects/test-engine/node_modules/ember-css-modules/lib/output-styles-preprocessor.js:42:32)
    at OutputStylesPreprocessor.toTree (/Users/devers/Projects/test-engine/node_modules/ember-css-modules/lib/output-styles-preprocessor.js:27:21)
    at /Users/devers/Projects/test-engine/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/devers/Projects/test-engine/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/Users/devers/Projects/test-engine/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
    at Class.compileStyles (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/models/addon.js:788:33)
    at Class.treeForAddon (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/models/addon.js:662:27)
    at Class._treeFor (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/models/addon.js:517:33)
    at Class.treeFor (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/models/addon.js:477:21)
    at project.addons.map.addon (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/broccoli/ember-app.js:525:20)
    at Array.map (native)
    at EmberAddon.EmberApp.addonTreesFor (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/broccoli/ember-app.js:523:30)
    at EmberAddon._addonTree (/Users/devers/Projects/test-engine/node_modules/ember-cli/lib/broccoli/ember-app.js:921:36)
```

addon I've tested this in here: https://github.com/deverstalmage/test-engine

**Comment by dfreeman** [comment]
https://github.com/ember-cli/ember-cli/pull/6884 _may_ be related to this. I'll try your reproduction repo tomorrow with ember-cli#master and see if that makes a difference.

**Comment by dfreeman** [comment]
Looks like that was it—after a `yarn upgrade ember-cli` (to 2.12.1), everything seems to play nicely in that repo now.

**Comment by ynnoj** [comment]
I'm seeing this error when running tests in a engine consuming app. Strangely not locally, but only on CI 🤔

**Comment by dfreeman** [comment]
@ynnoj 🤔  Can you confirm your CI is running with ember-cli 2.12.1+?

**Comment by ynnoj** [comment]
@dfreeman Installing the published package (as opposed to from the Git repo) fixed this issue for me 👍
